(function (root) {
  var FILL = [
    'Fill this once. Paste it at the top of every prompt.',
    '',
    'DOTK_NAME=alice.k',
    'RDNS=k.alice',
    'HOST=https://alice-k.vercel.app',
    'LOOK=Scorpion desk, gold on black, large receive QR',
    'GITHUB_USER=your-github-username',
    '',
    'Never invent a kaspa: address. Never print a seed, PIN, or 64-hex.',
    'Official .k only: https://dotk.name · github.com/supertypo/dotk-sdk · github.com/supertypo/dotk-sdk-tx'
  ].join('\n');

  var P1 = [
    'ITERATION 1 — Clone Scorpion. Do not start empty.',
    '',
    'Fork https://github.com/mrzeku2000XTTT/KCC20-wallet into GITHUB_USER/DOTK_NAME-wallet.',
    'Open that fork in this session as the workspace.',
    '',
    'KEEP UNCHANGED:',
    'js/tx.js js/crypto.js js/kasware.js js/kaspire.js js/kassigner.js',
    'vendor/kaspa (entire WASM) vendor/kron-sdk',
    'Approve / PIN / KasWare sheets. Keys never leave the PWA origin.',
    'signPskt only signs listed P2PK funding indexes.',
    'Do not overwrite window.kasware if a real extension exists.',
    '',
    'CHANGE NOW:',
    '1. index.html title, apple-mobile-web-app-title, og:title → DOTK_NAME',
    '2. manifest.json name and short_name → DOTK_NAME (short_name max 12 chars)',
    '3. In index.html BEFORE any other script, add:',
    '   <script>',
    '     window.KCC20_WALLET_ORIGIN = "HOST";',
    '     window.KCC20_DOTK = "DOTK_NAME";',
    '     window.KCC20_RDNS = "RDNS";',
    '   </script>',
    '4. sdk.js: keep SDK_VERSION; scriptOrigin() already reads KCC20_WALLET_ORIGIN.',
    '   Announce uses KCC20_DOTK, KCC20_RDNS, and origin (sdk 179).',
    '5. releases.json: add a note that this fork is DOTK_NAME.',
    '',
    'Do not restyle CSS yet. Commit: "identity: DOTK_NAME".',
    'Done when: grep shows KCC20_DOTK in index.html and manifest name is DOTK_NAME.'
  ].join('\n');

  var P2 = [
    'ITERATION 2 — Face only. LOOK from the fill-in block.',
    '',
    'Restyle index.html chrome and css/app.css to match LOOK.',
    'Home title is DOTK_NAME. Hide TRADE KCC20, Compound, KRON 24H, A-Trade unless LOOK asks for them.',
    'You may change copy, colors, layout, lock-screen title, You tab name.',
    'You may hide Apps you do not want. Do not delete js/ or vendor/.',
    '',
    'Kaspa brand: keep assets/kas.svg as the default mark.',
    'Home must still show live KAS + KCC20 from the existing app.js data.',
    'Receive QR must render THIS wallet address in-page (qrcode), not a fake.',
    '',
    'Do not touch signing, UTXO selection, or node URLs.',
    'Commit: "face: LOOK".'
  ].join('\n');

  var P3 = [
    'ITERATION 3 — Make it a real PWA that iPhone and desktop can INSTALL.',
    '',
    'Scorpion currently UNREGISTERS service workers in index.html to bust cache.',
    'This fork MUST register a service worker so Add to Home Screen works.',
    '',
    'A. manifest.json must include:',
    '   name: DOTK_NAME',
    '   short_name: first label before .k, max 12 chars',
    '   start_url: "./index.html"',
    '   display: "standalone"',
    '   background_color and theme_color',
    '   icons: assets/icon.png 192 and 512 (purpose any maskable). If only 1024 exists, keep it AND add a 192 copy.',
    '   id: "https://HOST/"',
    '   scope: "./"',
    '',
    'B. index.html head must include:',
    '   <link rel="manifest" href="manifest.json">',
    '   <meta name="apple-mobile-web-app-capable" content="yes">',
    '   <meta name="mobile-web-app-capable" content="yes">',
    '   <meta name="apple-mobile-web-app-title" content="DOTK_NAME">',
    '   <link rel="apple-touch-icon" href="assets/icon.png">',
    '   <meta name="theme-color" content="#050506">',
    '',
    'C. Add sw.js at repo root:',
    '   self.addEventListener("install", function(e){ self.skipWaiting(); });',
    '   self.addEventListener("activate", function(e){ e.waitUntil(self.clients.claim()); });',
    '   self.addEventListener("fetch", function(e){',
    '     if (e.request.mode === "navigate") return;',
    '     e.respondWith(fetch(e.request).catch(function(){ return caches.match(e.request); }));',
    '   });',
    '',
    'D. REPLACE the block in index.html that calls serviceWorker.getRegistrations().unregister().',
    '   Register instead:',
    '   if ("serviceWorker" in navigator) {',
    '     navigator.serviceWorker.register("./sw.js");',
    '   }',
    '',
    'E. HTTPS only. Vercel provides this. file:// will not install.',
    'Commit: "pwa: installable DOTK_NAME".'
  ].join('\n');

  var P4 = [
    'ITERATION 4 — dApps must see DOTK_NAME on Connect.',
    '',
    'Confirm sdk.js announceProviders() sends:',
    '  info.name = DOTK_NAME',
    '  info.identity = DOTK_NAME',
    '  info.rdns = RDNS',
    '  info.kind = "dotk"',
    '',
    'Add a one-file test: demo-dapp.html in the repo (static).',
    'It loads THIS fork\'s sdk.js from HOST (after deploy you will set HOST).',
    'Button Connect calls:',
    '  const list = await window.kcc20.discoverWallets();',
    '  render list showing identity and rdns;',
    '  await window.kcc20.connect({ identity: "DOTK_NAME", origin: "HOST" });',
    '  const who = await window.kcc20.getIdentity();',
    'Show who.name and who.address. Never ask for a key.',
    '',
    'Allow popups. Connect only on a click.',
    'Commit: "discover: DOTK_NAME".'
  ].join('\n');

  var P5 = [
    'ITERATION 5 — Deploy and install.',
    '',
    '1. Push the fork to GitHub.',
    '2. Vercel: Import that repo. Framework: Other. Output: root. HTTPS on HOST.',
    '3. After first deploy, set HOST in index.html KCC20_WALLET_ORIGIN if it still says YOUR-HOST.',
    '4. Redeploy.',
    '5. Open HOST on desktop Chrome. DevTools → Application → Manifest must be valid.',
    '   Service worker must be activated (not unregistered).',
    '6. Open HOST on iPhone Safari. Share → Add to Home Screen. Icon is DOTK_NAME.',
    '   Opening from the home icon must be standalone (no Safari chrome).',
    '7. Open demo-dapp.html on another origin or the same HOST. Connect.',
    '   The picker / popup must show DOTK_NAME. PIN signs. No seed field.',
    '',
    'If Add to Home Screen is missing: HTTPS, manifest linked, 192 icon, SW registered.',
    'If Connect missing .k: KCC20_DOTK script tag before sdk.js, hard-refresh.',
    'You need GitHub + Vercel before step 11. The Connect DOT.K dApp pops HOST, not localhost.',
    'Commit after HOST is real: "deploy: HOST".'
  ].join('\n');

  var P6 = [
    'ITERATION 6 — Fix pass. Only if something failed.',
    '',
    'Report: PWA install yes/no, discoverWallets identities, connect identity, PIN sign yes/no.',
    'Fix only the failing layer. Do not rewrite tx.js.',
    'If SW unregisters itself, you left Scorpion\'s unregister block — delete it.',
    'If rdns is still app.kcc20.wallet, KCC20_RDNS is missing.',
    'If keys leaked into the UI, revert that commit immediately.',
    'Done when: installed PWA, Connect from a dApp shows DOTK_NAME, one real TN10 or mainnet tx optional.'
  ].join('\n');

  var P7 = [
    'ITERATION 7 — This must NOT look like Scorpion / KCC20 Wallet.',
    '',
    'The user complained the app is still Wallet 1, TRADE KCC20, Compound, A-Trade, Vault tab.',
    'That chrome is Scorpion. Strip it unless LOOK explicitly asks for it.',
    '',
    'REMOVE or hide from Home:',
    '- Wallet chip switcher ("Wallet 1") unless they have multiple keys',
    '- TRADE KCC20 row, Compound, KRON 24H, A-Trade tab',
    '- Scorpion / You marketing copy, TTT logos if LOOK is not Scorpion',
    '',
    'REPLACE Home with DOTK_NAME layout:',
    '- Title: DOTK_NAME (not Wallet 1, not KCC20 Wallet)',
    '- Identity, live KAS, live KCC20, Receive QR in-page, Send in-page',
    '- Tab bar labels: Home / Activity / You only, unless LOOK needs more',
    '- Lock screen title DOTK_NAME',
    '- Connect popup title DOTK_NAME (dappConnect.js strings that say KCC20 Wallet)',
    '',
    'Keep the signer. Delete is for UI. Do not delete tx.js.',
    'Commit: "face: not scorpion — DOTK_NAME".',
    'Done when a screenshot would not be mistaken for kcc-20-wallet.vercel.app.'
  ].join('\n');

  var P8 = [
    'ITERATION 8 — Connect must pop THIS PWA, not Scorpion.',
    '',
    'If a dApp loads https://kcc-20-wallet.vercel.app/sdk.js, Connect opens Scorpion.',
    'THIS fork must ship its own sdk.js from HOST.',
    '',
    '1. index.html MUST set before sdk.js:',
    '   window.KCC20_WALLET_ORIGIN = "HOST"',
    '   window.KCC20_DOTK = "DOTK_NAME"',
    '   window.KCC20_RDNS = "RDNS"',
    '2. demo-dapp.html on THIS repo loads:',
    '   <script src="HOST/sdk.js?v=179"></script>',
    '   NOT kcc-20-wallet.vercel.app/sdk.js',
    '3. Button: Connect DOTK_NAME',
    '     await window.kcc20.connect({ identity: "DOTK_NAME", origin: "HOST" })',
    '   The popup URL must be HOST/index.html?dapp=1 — inspect the popup address bar.',
    '4. announceProviders info.origin must be HOST.',
    '',
    'If the popup URL is kcc-20-wallet.vercel.app you failed this pass. Fix origin.',
    'Commit: "connect pops HOST".'
  ].join('\n');

  var P9 = [
    'ITERATION 9 — Third-party dApps using the official SDK.',
    '',
    'A site that only loaded Scorpion sdk.js can still open THIS wallet:',
    '  await window.kcc20.connect({ identity: "DOTK_NAME", origin: "HOST" })',
    'or',
    '  await window.kcc20.connect({ identity: "DOTK_NAME" })',
    'after adding a row to https://kcc20-sdk.vercel.app/dotk-wallets.json :',
    '  { "identity": "DOTK_NAME", "rdns": "RDNS", "origin": "HOST", "name": "DOTK_NAME" }',
    '',
    'Open a PR on mrzeku2000XTTT/kcc20-sdk adding that row, OR document HOST in README.',
    'Test from a blank page that uses ONLY https://kcc-20-wallet.vercel.app/sdk.js?v=179',
    'and connect({ identity, origin: HOST }). Popup must be HOST, chrome must say DOTK_NAME.',
    'Commit: "registry: DOTK_NAME → HOST".'
  ].join('\n');

  var P10 = [
    'ITERATION 10 — Buy the official .k name with THIS wallet\'s address.',
    '',
    'DOTK_NAME must be a real L1 covenant name from official Dot.K.',
    'It identifies the entire wallet: the deed owner IS the Receive address of this PWA.',
    '',
    'OFFICIAL ONLY — never a fake JSON name, never .kas inscriptions, never knsdomains.org:',
    '  Site:     https://dotk.name',
    '  Read SDK: https://github.com/supertypo/dotk-sdk     npm @dotk/sdk',
    '  Write:    https://github.com/supertypo/dotk-sdk-tx   npm @dotk/sdk-tx',
    '  API:      https://api.dotk.name   (TN10: https://api-tn10.dotk.name)',
    '',
    '1. Unlock THIS PWA. Copy the Receive address (kaspa:q… or kaspatest:q…).',
    '   That address is the only owner allowed. Do not buy with KasWare if this PWA has its own PIN key.',
    '   Do not buy with a different wallet. The deed must sit on THIS key.',
    '',
    '2. Add a You → Settings (or Home) tile "Buy .k".',
    '   Load @dotk/sdk in the browser (esm.sh @dotk/sdk@2.0.0).',
    '   const dotk = new Dotk()  // mainnet. For TN10: new Dotk({ network: "testnet-10" })',
    '   const q = dotk.quote("DOTK_NAME")',
    '   const free = await dotk.available("DOTK_NAME")',
    '   Show feeKas = q.fee/1e8, totalToFundKas = q.totalToFund/1e8, free yes/no.',
    '   Prices (plus 2 KAS bond returned on release): 5+ chars 40 KAS, 4=250, 3=1000, 2=2000, 1=4000.',
    '',
    '3. Register with @dotk/sdk-tx Registrar. Signer wraps THIS PWA:',
    '   sign(request) {',
    '     const indexes = [...(request.fundingInputs||[]), ...(request.ownerSigInputs||[])]',
    '       .map(i => ({ index: i, sighashType: 1 }));',
    '     return window.kcc20',
    '       ? window.kcc20.signPskt({ txJsonString: request.txJson, options: { signInputs: indexes } })',
    '       : /* in-PWA native: the same Approve sheet this wallet already uses for signPskt */',
    '         signPsktJson(request.txJson, indexes);',
    '   }',
    '   signInputs.index is GLOBAL tx.inputs[]. SIGHASH_ALL only.',
    '   Do not sign covenant/gap seats that already have scripts unless they are in ownerSigInputs.',
    '   register() is commit then waitForCommit then reveal. Both halves must be planned before the first Approve.',
    '',
    '4. After ACTIVE: await dotk.namesOf(THIS_ADDRESS) must include DOTK_NAME.',
    '   await dotk.addressFor("DOTK_NAME") must equal THIS_ADDRESS.',
    '   Stamp window.KCC20_DOTK = "DOTK_NAME" if it was a placeholder.',
    '',
    '5. Optional records (still official sdk-tx planRecords):',
    '   { url: "HOST", primary: true }',
    '   url is the Vercel origin of THIS PWA. That is how a dApp finds the signer.',
    '',
    'If you cannot wire sdk-tx this pass: open https://dotk.name IN A TAB, Connect using THIS PWA',
    '(sdk 179 connect from that origin — they must add Scorpion; until then use the in-PWA Buy tile).',
    'Still: the paying address must be THIS Receive address.',
    '',
    'Never invent a name in localStorage. Never print a seed.',
    'Commit: "dotk: bought DOTK_NAME on official registry".',
    'Done when lookup(DOTK_NAME).kind === "active" and addressFor === this wallet.'
  ].join('\n');

  var P11 = [
    'ITERATION 11 — GitHub + Vercel HOST, then the official dApp Connects YOUR PWA.',
    '',
    'A dApp cannot pop a wallet that only lives on localhost. Publish HOST.',
    '',
    'A. GitHub',
    '   git remote -v must be github.com/GITHUB_USER/… (the fork from step 1).',
    '   git add -A && git commit && git push origin main.',
    '   If there is no remote: gh repo create GITHUB_USER/DOTK_NAME-wallet --public --source=. --remote=origin --push',
    '',
    'B. Vercel',
    '   Import that GitHub repo. Framework: Other. Output: root. HTTPS on.',
    '   Production URL is HOST, e.g. https://DOTK_NAME-wallet.vercel.app',
    '   Set in index.html BEFORE sdk.js:',
    '     window.KCC20_WALLET_ORIGIN = "HOST"',
    '     window.KCC20_DOTK = "DOTK_NAME"',
    '     window.KCC20_RDNS = "RDNS"',
    '   Redeploy. Open HOST. Receive address is the same key as step 10.',
    '',
    'C. Bind name → HOST',
    '   Official records.url = HOST (sdk-tx saveRecords).',
    '   Add a row to https://kcc20-sdk.vercel.app/dotk-wallets.json :',
    '     { "identity": "DOTK_NAME", "rdns": "RDNS", "origin": "HOST", "name": "DOTK_NAME" }',
    '',
    'D. Prove it on the live dApp',
    '   Open https://kcc20-sdk.vercel.app/dotk-dapp.html',
    '   Top right: Connect DOT.K wallet.',
    '   Identity = DOTK_NAME. Origin = HOST (the Vercel URL from B).',
    '   Connect must popup HOST/index.html?dapp=1 — inspect the address bar.',
    '   Approve in YOUR PWA. The dApp shows DOTK_NAME + your kaspa: address.',
    '   Official lookup: addressFor(DOTK_NAME) must equal the connected account.',
    '   Tap Prove. sendKaspa dust to self. Approve in YOUR PWA. Print txId.',
    '',
    'If popup is kcc-20-wallet.vercel.app you loaded Scorpion sdk without origin. Pass origin: HOST.',
    'If Connect missing: HOST must be https, allow popups, sdk.js on HOST.',
    'If name mismatch: you bought the .k with a different key — redo step 10 from THIS PWA.',
    'Commit: "deploy: HOST + Connect DOT.K".',
    'Done when the dApp at kcc20-sdk.vercel.app/dotk-dapp.html pops HOST and a Prove tx confirms.'
  ].join('\n');

  var P12 = [
    'ITERATION 12 — Verified Dot.K. Make THIS wallet discoverable as the DOTK_NAME domain.',
    '',
    'Owning the name (step 10) is WHO. Publishing HOST (step 11) is WHERE.',
    'This pass binds them so a dApp that only knows "DOTK_NAME" finds HOST and paints Verified.',
    '',
    'Never paint Verified from localStorage, a typed string, a JSON nickname, or a .kas inscription.',
    'Official only: https://dotk.name · github.com/supertypo/dotk-sdk · github.com/supertypo/dotk-sdk-tx · https://api.dotk.name',
    '',
    'A wallet is VERIFIED only when these four live facts agree:',
    '',
    '  1. DEED    lookup(DOTK_NAME).kind === "active"',
    '             addressFor(DOTK_NAME) === THIS PWA Receive address',
    '  2. DOMAIN  records.url === HOST     (https origin of THIS PWA, no trailing slash)',
    '             primary: true',
    '  3. POPUP   kcc20.connect({ identity: "DOTK_NAME" })   // origin omitted on purpose',
    '             opens HOST/index.html?dapp=1',
    '  4. CLAIM   window.KCC20_DOTK === "DOTK_NAME"',
    '             getIdentity().name === "DOTK_NAME"',
    '             getAccounts()[0] === addressFor(DOTK_NAME)',
    '',
    'If 1 holds and 2 is empty they OWN the name and the wallet is not DISCOVERABLE.',
    'Discoverable means the .k domain itself points at the PWA.',
    '',
    'A. Publish the domain record — this IS making the wallet a .k domain',
    '',
    '   Load @dotk/sdk-tx in THIS PWA. Same signer as step 10 (signPskt by global index, SIGHASH_ALL).',
    '',
    '   const plan = await registrar.planRecords("DOTK_NAME", {',
    '     url: "HOST",',
    '     primary: true,',
    '     "com.github": "GITHUB_USER/DOTK_NAME-wallet"',
    '   });',
    '   Show plan.fee. User Approves. await registrar.submit(plan);',
    '   // shorthand: await registrar.saveRecords("DOTK_NAME", { url: "HOST", primary: true, "com.github": "..." })',
    '',
    '   url MUST be https. Refuse javascript:, data:, http:. HOST has no trailing slash.',
    '   A card costs CARD_VALUE (0.5 KAS) sitting beside the deed; the spender can reclaim it later.',
    '',
    '   Wait for confirm. Then:',
    '     const found = await dotk.resolveName("DOTK_NAME")',
    '     origin of found.records.url must equal HOST.',
    '     found.address must equal THIS_ADDRESS.',
    '',
    'B. This PWA claims the name — so HOST answers as DOTK_NAME',
    '',
    '   index.html BEFORE sdk.js:',
    '     window.KCC20_WALLET_ORIGIN = "HOST"',
    '     window.KCC20_DOTK = "DOTK_NAME"',
    '     window.KCC20_RDNS = "RDNS"',
    '',
    '   Add public files so others can fetch the claim without opening the app.',
    '   Same JSON at /.well-known/dotk.json AND /dotk.json :',
    '   {',
    '     "identity": "DOTK_NAME",',
    '     "rdns": "RDNS",',
    '     "origin": "HOST",',
    '     "name": "DOTK_NAME"',
    '   }',
    '',
    '   announceProviders info.identity = DOTK_NAME, info.origin = HOST, info.kind = "dotk".',
    '',
    'C. Catalog — so a dApp that only loaded Scorpion sdk.js still finds you',
    '',
    '   PR a row to https://kcc20-sdk.vercel.app/dotk-wallets.json :',
    '   { "identity": "DOTK_NAME", "rdns": "RDNS", "origin": "HOST", "name": "DOTK_NAME" }',
    '',
    '   Official records.url is the source of truth. The JSON is a directory.',
    '',
    'D. Verified chip in THIS PWA',
    '',
    '   You → Identity (or Home). Title is DOTK_NAME.',
    '   Fetch live: esm.sh @dotk/sdk@2.0.0 , new Dotk(), resolveName + lookup.',
    '   Paint "Verified" ONLY when A + B hold on that live answer.',
    '   Otherwise paint the missing fact: "Buy the name" / "Set records.url" / "HOST mismatch" / "Wrong key".',
    '   Never a green badge on a placeholder.',
    '',
    'E. Prove discoverability on the live dApp — origin field EMPTY',
    '',
    '   Open https://kcc20-sdk.vercel.app/dotk-dapp.html',
    '   Identity = DOTK_NAME. Clear the origin field.',
    '   Lookup official .k — origin must fill from records.url.',
    '   Connect DOT.K wallet — popup address bar is HOST/index.html?dapp=1.',
    '   Status shows Verified.',
    '   Prove self-send still Approves in THIS PWA.',
    '',
    '   Pin sdk.js?v=179. connect({ identity }) uses records.url, then the registry.',
    '   If origin is still blank after Lookup: records.url is missing — redo A.',
    '',
    'If popup is kcc-20-wallet.vercel.app, records.url / registry still point at Scorpion. Fix A and C.',
    'If Verified stays off after Connect: they bought the .k with a different key — redo step 10 from THIS PWA.',
    'Commit: "dotk: verified + discoverable DOTK_NAME".',
    'Done when the live dApp, given only DOTK_NAME, pops HOST and shows Verified.'
  ].join('\n');

  var ALL = [FILL, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12].join('\n\n========== NEXT ITERATION ==========\n\n');

  var STEPS = [
    { id: 'fill', n: '0', title: 'Fill this first', blurb: 'Name, host, look. Paste on every later prompt.', text: FILL },
    { id: 'core', n: '1', title: 'Fork the core', blurb: 'Clone Scorpion. Stamp .k identity. Do not restyle yet.', text: P1 },
    { id: 'face', n: '2', title: 'Design the face', blurb: 'HTML/CSS only. Live KAS and QR stay real.', text: P2 },
    { id: 'pwa', n: '3', title: 'Make it installable', blurb: 'Manifest, Apple tags, service worker. Replace Scorpion’s unregister.', text: P3 },
    { id: 'dapp', n: '4', title: 'Be visible to dApps', blurb: 'Announce alice.k. Ship a tiny Connect test page.', text: P4 },
    { id: 'ship', n: '5', title: 'Deploy and Add to Home Screen', blurb: 'Vercel HTTPS. iPhone standalone. Desktop install.', text: P5 },
    { id: 'fix', n: '6', title: 'Fix pass', blurb: 'Only if install or Connect failed.', text: P6 },
    { id: 'notscorpion', n: '7', title: 'Stop looking like Scorpion', blurb: 'Strip Wallet 1, TRADE, Compound, A-Trade. Home is DOTK_NAME.', text: P7 },
    { id: 'popup', n: '8', title: 'Connect pops YOUR PWA', blurb: 'demo-dapp loads HOST/sdk.js. Popup URL is HOST, not kcc-20-wallet.', text: P8 },
    { id: 'registry', n: '9', title: 'Any dApp can open you', blurb: 'connect({ identity, origin }) or a row in dotk-wallets.json.', text: P9 },
    { id: 'buy', n: '10', title: 'Buy official .k with THIS address', blurb: 'dotk.name / @dotk/sdk-tx. Deed owner is this PWA Receive address.', text: P10 },
    { id: 'vercel', n: '11', title: 'GitHub + Vercel, then Connect DOT.K', blurb: 'Publish HOST. The dApp pops your Vercel PWA and you Approve.', text: P11 },
    { id: 'verified', n: '12', title: 'Verified + discoverable as .k', blurb: 'records.url = HOST. Connect with the name alone. Verified only when deed, HOST, and account agree.', text: P12 }
  ];

  root.KCC20_DOTK_PROMPT = ALL;
  root.KCC20_DOTK_STEPS = STEPS;
  root.KCC20_copyDotkPrompt = function (id) {
    var text = ALL;
    if (id) {
      var s = STEPS.filter(function (x) { return x.id === id; })[0];
      if (s) text = s.text;
    }
    return navigator.clipboard.writeText(text);
  };
})(typeof window !== 'undefined' ? window : this);
